# Generated by Django 6.0.2 on 2026-03-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LecturaTermometro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numTermometro', models.IntegerField(default=0)),
                ('temperatura', models.FloatField(default=0)),
                ('fechaHoraMedida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
