# Generated by Django 6.0.2 on 2026-04-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LectorTermometro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturatermometro',
            name='numTermometro',
            field=models.CharField(max_length=10),
        ),
    ]
