# Generated by Django 6.0.2 on 2026-04-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LectorTermometro', '0002_alter_lecturatermometro_numtermometro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturatermometro',
            old_name='numTermometro',
            new_name='idTermometro',
        ),
        migrations.AlterField(
            model_name='lecturatermometro',
            name='temperatura',
            field=models.FloatField(null=True),
        ),
    ]
