# Generated by Django 6.0.2 on 2026-04-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LectorTermometro', '0003_rename_numtermometro_lecturatermometro_idtermometro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoMedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idElemento', models.CharField(max_length=10)),
                ('tipoElemento', models.CharField(max_length=10)),
            ],
        ),
    ]
