# Generated by Django 6.0.2 on 2026-04-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LectorTermometro', '0004_elementomedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoElemento', models.CharField(max_length=15)),
                ('minimoRango', models.FloatField(default=10)),
                ('maximoRango', models.FloatField(default=20)),
            ],
        ),
        migrations.AlterField(
            model_name='elementomedido',
            name='tipoElemento',
            field=models.CharField(max_length=15),
        ),
    ]
