# Generated by Django 5.2.14 on 2026-05-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LectorTermometro', '0005_tipoelemento_alter_elementomedido_tipoelemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementomedido',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lecturatermometro',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tipoelemento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
