# Generated by Django 5.2.14 on 2026-06-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LectorTermometro', '0007_alter_elementomedido_id_alter_lecturatermometro_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementomedido',
            name='descripElemento',
            field=models.CharField(default='', max_length=20),
        ),
    ]
